-- Rollback data tables
BEGIN;

DROP TABLE IF EXISTS instance_stats CASCADE;
DROP TABLE IF EXISTS templates CASCADE;
DROP TABLE IF EXISTS media_files CASCADE;
DROP TABLE IF EXISTS groups CASCADE;
DROP TABLE IF EXISTS contacts CASCADE;
DROP TABLE IF EXISTS api_logs CASCADE;
DROP TABLE IF EXISTS webhook_logs CASCADE;
DROP TABLE IF EXISTS messages CASCADE;

COMMIT;
